# Generated by Django 4.1.2 on 2022-11-11 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('url', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Languages',
                'db_table': 'languages',
                'managed': True,
            },
        ),
    ]
