# Generated by Django 4.1.2 on 2022-12-19 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languages',
            name='code',
            field=models.CharField(default='en', max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='languages',
            name='name',
            field=models.CharField(default='English', max_length=30),
        ),
        migrations.AlterField(
            model_name='languages',
            name='url',
            field=models.CharField(default='en', max_length=30),
        ),
    ]
