# Generated by Django 4.1.2 on 2022-12-23 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_alter_languages_code_alter_languages_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languages',
            name='url',
            field=models.CharField(blank=True, default='en', max_length=30),
        ),
    ]
