# Generated by Django 4.1.2 on 2023-01-02 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0003_alter_languages_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languages',
            name='code',
            field=models.CharField(max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='languages',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='languages',
            name='url',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
