# Generated by Django 4.1.2 on 2022-12-23 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0003_alter_languages_url'),
        ('category_default', '0003_alter_tags_tag_mid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_language', to='directory.languages'),
        ),
    ]
