# Generated by Django 4.1.2 on 2022-12-28 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_default', '0004_alter_tags_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='parent',
        ),
        migrations.AddField(
            model_name='categories',
            name='parent',
            field=models.ManyToManyField(blank=True, null=True, to='category_default.categories'),
        ),
    ]
