# Generated by Django 4.1.3 on 2023-03-28 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_default', '0006_alter_anekdots_options_anekdots_show_for_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='alternative',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='behave_as_tag',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='date_modified',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='visible',
        ),
        migrations.RemoveField(
            model_name='tags',
            name='alternative',
        ),
        migrations.RemoveField(
            model_name='tags',
            name='anchor1',
        ),
        migrations.RemoveField(
            model_name='tags',
            name='anchor10',
        ),
        migrations.RemoveField(
            model_name='tags',
            name='anchor2',
        ),
        migrations.RemoveField(
            model_name='tags',
            name='anchor3',
        ),
        migrations.RemoveField(
            model_name='tags',
            name='anchor4',
        ),
        migrations.RemoveField(
            model_name='tags',
            name='anchor5',
        ),
        migrations.RemoveField(
            model_name='tags',
            name='anchor6',
        ),
        migrations.RemoveField(
            model_name='tags',
            name='anchor7',
        ),
        migrations.RemoveField(
            model_name='tags',
            name='anchor8',
        ),
        migrations.RemoveField(
            model_name='tags',
            name='anchor9',
        ),
        migrations.RemoveField(
            model_name='tags',
            name='visible',
        ),
        migrations.AlterField(
            model_name='categories',
            name='parent',
            field=models.ManyToManyField(blank=True, to='category_default.categories'),
        ),
    ]
