# Generated by Django 4.1.2 on 2023-03-29 00:38

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_default', '0007_remove_categories_alternative_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tags',
            old_name='tag_down',
            new_name='parent_tag',
        ),
        migrations.RemoveField(
            model_name='anekdots',
            name='show_for_tags',
        ),
        migrations.RemoveField(
            model_name='tags',
            name='tag_mid',
        ),
        migrations.AlterField(
            model_name='anekdots',
            name='tags',
            field=models.ManyToManyField(blank=True, to='category_default.tags'),
        ),
        migrations.AlterField(
            model_name='anekdots',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='tags',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
