# Generated by Django 4.1.2 on 2023-03-30 13:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_default', '0008_rename_tag_down_tags_parent_tag_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='parent',
            new_name='sub_categories',
        ),
        migrations.AlterField(
            model_name='anekdots',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='anekdots_tags', to='category_default.tags'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='records_per_page',
            field=models.IntegerField(default=20, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(50)]),
        ),
    ]
