# Generated by Django 4.1.2 on 2023-03-31 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_default', '0009_rename_parent_categories_sub_categories_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tags',
            old_name='parent_tag',
            new_name='sub_tags',
        ),
        migrations.AlterField(
            model_name='categories',
            name='sub_categories',
            field=models.ManyToManyField(blank=True, related_name='parent_category', to='category_default.categories'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='tags',
            field=models.ManyToManyField(blank=True, to='category_default.tags'),
        ),
    ]
