# Generated by Django 4.1.2 on 2023-05-16 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_default', '0011_categories_behave_as_tag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags',
            name='only_subtag',
            field=models.BooleanField(default=False),
        ),
    ]
