# Generated by Django 4.1.2 on 2023-05-20 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0004_alter_languages_code_alter_languages_name_and_more'),
        ('category_default', '0013_alter_categories_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.languages'),
        ),
    ]
